CREATE TABLE CUSTOMERS (
    ID STRING,
    NAME STRING,
    PLACE STRING
);

SELECT ID, NAME, PLACE FROM CUSTOMERS WHERE ID = 1 AND NAME = 'RECEP KARA' ORDER BY ID DESC

UPDATE CUSTOMERS SET NAME = 'RECEP KARA', ID = 2 WHERE ID = 1;

DELETE FROM CUSTOMERS WHERE ID = 2 AND NAME = 'RECEP KARA'

INSERT INTO CUSTOMERS VALUES (1, 'RECEP KARA', 'ISTANBUL')

DROP TABLE CUSTOMERS